/*
 * @FilePath: \3D防汛作战\src\pages\modules\dialog\icm-progress-query\entity\status.js
 * @Author: zhangyang
 * @Date: 2022-07-01 11:09:27
 * @LastEditors: zhangyang
 * @LastEditTime: 2022-07-01 15:21:44
 * @Description: 
 */
import {
    IMITATE_UNKNOWN,
    IMITATE_NO_RESULT,
    IMITATE_IN_PROGRESS,
    IMITATE_SUCCESS,
    IMITATE_RUN_FAIL,
    IMITATE_QUERY_ERROR,
    SUB_IMITATE_INTERRUPT,
    SUB_IMITATE_WARNING,
    SUB_IMITATE_OK
} from "../share/context";
import {
    IMITATE_UNKNOWN_TIPS,
    IMITATE_NO_RESULT_TIPS,
    IMITATE_IN_PROGRESS_TIPS,
    IMITATE_SUCCESS_TIPS,
    IMITATE_RUN_FAIL_TIPS,
    IMITATE_QUERY_ERROR_TIPS,
    SUB_IMITATE_INTERRUPT_TIPS,
    SUB_IMITATE_WARNING_TIPS,
    SUB_IMITATE_OK_TIPS
} from "../share/tips";

const STATUS_MAPPING = {
    [IMITATE_UNKNOWN]: IMITATE_UNKNOWN_TIPS,
    [IMITATE_NO_RESULT]: IMITATE_NO_RESULT_TIPS,
    [IMITATE_IN_PROGRESS]: IMITATE_IN_PROGRESS_TIPS,
    [IMITATE_SUCCESS]: IMITATE_SUCCESS_TIPS,
    [IMITATE_RUN_FAIL]: IMITATE_RUN_FAIL_TIPS,
    [IMITATE_QUERY_ERROR]: IMITATE_QUERY_ERROR_TIPS,
    [SUB_IMITATE_INTERRUPT]: SUB_IMITATE_INTERRUPT_TIPS,
    [SUB_IMITATE_WARNING]: SUB_IMITATE_WARNING_TIPS,
    [SUB_IMITATE_OK]: SUB_IMITATE_OK_TIPS
};

export default (status) => {
    return STATUS_MAPPING[status] ?? STATUS_MAPPING[IMITATE_UNKNOWN];
}
